services:
  postgres_alex-brot:
    image: postgres:17
    container_name: postgres_alex-brot
    environment:
      POSTGRES_USER: alex-brot
      POSTGRES_PASSWORD: alex-brot
      POSTGRES_DB: alex-brot
    ports:
      - "5432:5432"
    volumes:
      - postgres_alex-brot:/var/lib/postgresql/data
volumes:
  postgres_alex-brot:
